### ISSUE TITLE
I don't know how how to receive message from peer. 

### ISSUE THREAD

**Issue by schrodog** [namuyan/p2p-python#10]
As topic stated, not sure how to use this library. Hope has more clear guideline.

**Comment by namuyan** [comment]
Hello, what don't you understand?
Please point out to [how-to-use](https://github.com/namuyan/p2p-python#how-to-use) by concrete comment.

About **how to receive message**, you should read [DIRECT_CMD.md](https://github.com/namuyan/p2p-python/blob/master/doc/DIRECT_CMD.md). The example is simple, I think.
