### ISSUE TITLE
ImportError: cannot import name 'Debug'

### ISSUE THREAD

**Issue by lapitskiy** [namuyan/p2p-python#2]
Hello, i try start this - https://github.com/namuyan/p2p-python/blob/master/doc/CHANNEL.md

```
Traceback (most recent call last):
  File "C:/Users/Egor/PycharmProjects/untitled/consensus_client.py", line 23, in <module>
    from p2p_python.config import C, V, Debug
ImportError: cannot import name 'Debug'
```

Can you help me?

**Comment by lapitskiy** [comment]
sry, i check this problem https://pypi.org/project/nem-ed25519/0.0.6/

**Comment by lapitskiy** [comment]
done. repository in PyCharm not same this repository.

**Comment by namuyan** [comment]
Thank you for report.
I update pip now.
